"""Field-engine runtime - a NORMAL HF model, loads through the standard API:
    AutoModelForCausalLM.from_pretrained(path, trust_remote_code=True)
    (recommended: dtype="bfloat16", low_cpu_mem_usage=True)
Generated by hf_pipeline.py. Requires transformers>=5
(SparseMoeBlock.forward -> Tensor).

Idea: no explicit expert weights are stored. Instead there is a "field":
centroids (w*bd) + low-rank factors U,V + coordinates C. The "movement seed"
c(z) = z @ C is computed from the router:
    z = top-k router weights scattered over the expert vocabulary
    gu(x) = x@wGud^T + (x@Vgu * cgu)@Ugu^T      # fused gate+up
    h = silu(gate_part) * up_part
    y  = h@wDnd^T + (h@Vdn * cdn)@Udn^T         # down
One FFN pass instead of top-k passes (FLOPs/2 at top-2, ~x8 at top-8).

Routers (config.field.router_kind):
  softmax       - OLMoE and relatives: softmax -> top-k -> (weight
                  normalization)
  sigmoid_bias  - hy_v3 (NanoColibri): sigmoid -> +e_score_correction_bias ->
                  top-k -> normalization -> *router_scaling_factor;
                  shared experts (dff_shexp) are always active and added to
                  the field output (fp32).
"""
import torch
import torch.nn as nn
from transformers import @@BASE@@
from @@ROUTER_MOD@@ import @@ROUTER@@
from transformers.activations import ACT2FN


class FieldSharedMLP(nn.Module):
    """hy_v3 shared experts (always active): parameter names match the base
    ones (shared_experts.gate_proj.weight etc.) so the artifact weights are
    picked up by the stock loader."""

    def __init__(self, d, dff, act_fn):
        super().__init__()
        self.gate_proj = nn.Linear(d, dff, bias=False)
        self.up_proj = nn.Linear(d, dff, bias=False)
        self.down_proj = nn.Linear(dff, d, bias=False)
        self.act_fn = act_fn

    def forward(self, x):
        return self.down_proj(self.act_fn(self.gate_proj(x)) * self.up_proj(x))


class FieldSparseMoe(nn.Module):
    """SparseMoeBlock replacement: same router, experts assembled from the
    field."""

    def __init__(self, config):
        super().__init__()
        self.fi = dict(config.field)                   # also available in forward
        fi = self.fi
        d, dff, r = fi["d_model"], fi["d_ff"], fi["rank"]
        self.kind = str(fi.get("router_kind", "softmax"))
        self.gate = @@ROUTER@@(config)                 # router untouched (base weight)
        if self.kind == "sigmoid_bias":
            self.register_buffer("e_score_correction_bias",
                                 torch.zeros(fi["n_exp"]))
        self.act_fn = ACT2FN[fi.get("hidden_act", "silu")]
        dffs = int(fi.get("dff_shexp", 0))
        # name shared_experts matches the base -> artifact weights are picked up
        self.shared_experts = FieldSharedMLP(d, dffs, self.act_fn) if dffs else None
        for nm, out, inp in (("gu", 2 * dff, d), ("dn", d, dff)):
            self.register_parameter(f"w{nm}d", nn.Parameter(torch.zeros(out, inp)))
            self.register_parameter(f"U{nm}", nn.Parameter(torch.zeros(out, r)))
            self.register_parameter(f"V{nm}", nn.Parameter(torch.zeros(inp, r)))
        self.Cgu = nn.Parameter(torch.zeros(fi["n_exp"], r))
        self.Cdn = nn.Parameter(torch.zeros(fi["n_exp"], r))

    def forward(self, hidden_states):
        fi = self.fi
        B, T, d = hidden_states.shape
        x = hidden_states.reshape(-1, d)
        if self.kind == "sigmoid_bias":                # gate normalizes and scales itself
            logits, w, idx = self.gate(x, self.e_score_correction_bias)
            z = torch.zeros_like(logits).scatter_(-1, idx, w)
        else:
            gout = self.gate(x)
            if isinstance(gout, (tuple, list)):        # v5 router: (logits, scores, idx)
                logits, scores, idx = gout[0], gout[1], gout[2]
            else:                                      # plain Linear router
                logits = gout
                probs = torch.softmax(logits.float(), dim=-1)
                scores, idx = torch.topk(probs, fi["top_k"], dim=-1)
                if fi.get("norm_topk"):
                    scores = scores / scores.sum(-1, keepdim=True)
            z = torch.zeros_like(logits).scatter_(-1, idx, scores)
        z = z.to(hidden_states.dtype)      # sigmoid router computes in fp32
        cgu, cdn = z @ self.Cgu, z @ self.Cdn          # movement seed (T,r)
        gu = x @ self.wgud.t() + (x @ self.Vgu * cgu) @ self.Ugu.t()
        g, u = gu.chunk(2, dim=-1)
        h = self.act_fn(g) * u
        y = h @ self.wdnd.t() + (h @ self.Vdn * cdn) @ self.Udn.t()
        if self.shared_experts is not None:
            ys = self.shared_experts(x)
            y = (y.float() + ys.float()).to(y.dtype)   # fp32 combine, same as base
        return y.view(B, T, -1)


class FieldForCausalLM(@@BASE@@):
    """Base architecture with every MoE block replaced by the field."""

    def __init__(self, config):
        super().__init__(config)
        n = 0
        for name, mod in list(self.named_modules()):
            if hasattr(mod, "experts") and hasattr(mod, "gate"):
                parent = self.get_submodule(name.rsplit(".", 1)[0]) if "." in name else self
                setattr(parent, name.rsplit(".", 1)[-1], FieldSparseMoe(config))
                n += 1
        expected = config.field["n_layers"]
        if n != expected:
            raise RuntimeError(f"replaced {n} MoE blocks, expected {expected}")
